### ISSUE TITLE
Error with running TILPRED

### ISSUE THREAD

**Issue by Saumya513** [carmonalab/TILPRED#4]
I converted my seurat object to SingleCellExperiment object and run TILPRED on it.
But it again gave me the error:
Error in .local(exprMat, plotStats, nCores, mctype, keepZeroesAsNA, verbose, :
unused argument (splitByBlocks = TRUE)

This error also shows up while running the test data that was used on the Github page.
Could anyone please help me with this?

Thank you

**Comment by sjcarmona** [comment]
Hi, TILPRED is no longer maintained. Please use [Projectils](https://github.com/carmonalab/ProjecTILs) instead
